# Mde basic infomation

MDE_APP_TARGET = mde
MDE_VERSION = 2.0.0
MDE_COMPAT_VERSION = $$MDE_VERSION

MDE_SOURCE_ROOT = $$PWD
MDE_BUILD_ROOT = $$shadowed($$PWD)

# build path
MDE_BIN_PATH = $$MDE_BUILD_ROOT/bin
MDE_LIBRARY_PATH = $$MDE_BUILD_ROOT/lib
MDE_APP_PATH = $$MDE_BIN_PATH
MDE_PLUGIN_PATH = $$MDE_LIBRARY_PATH/plugins
MDE_DOC_PATH = $$MDE_BUILD_ROOT/share/doc
MDE_DATA_PATH = $$MDE_BUILD_ROOT/share
MDE_TRANSLATION_PATH = $$MDE_BUILD_ROOT/share/translations

