#ifndef GENERALSETTINGS_GLOBAL_H
#define GENERALSETTINGS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERALSETTINGS_LIBRARY)
#  define GENERALSETTINGSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERALSETTINGSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALSETTINGS_GLOBAL_H
